---

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Install the gpg key for nodejs LTS
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_14.x focal main"
    state: present
    update_cache: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "tar", "gzip"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

#- name: Creates directory
#  file:
#    path: ~/web
#    state: directory

#- name: Copy index test page
#  template:
#    src: "files/index.js"
#    dest: "~/web/index.js"

#- name: Executing node
#  shell: |
#    pm2 start ~/web/index.js -f
