---
- name: Creates web directory
  become_user: ubuntu
  become: yes
  file:
    path: /home/ubuntu/web
    state: directory

- name: Copy files
  become_user: ubuntu
  become: yes 
  copy: 
    src: ~/project/backend.tar
    dest: /home/ubuntu/web

- name: Unarchive
  become_user: ubuntu
  become: yes 
  unarchive: 
    src: ~/project/backend.tar
    dest: /home/ubuntu/web

- name: Execute node
  become: true 
  shell: |
    cd /home/ubuntu/web
    pm2 start npm --name backend -- start