---
- name: Creates web directory
  become_user: ubuntu
  become: yes
  file:
    path: /home/ubuntu/web
    state: directory

#- name: Copy files
#  become_user: ubuntu
#  become: yes 
#  copy: 
#    src: ~/project/backend.tar
#    dest: /home/ubuntu/web

- name: Unarchive
  become_user: ubuntu
  become: yes 
  unarchive: 
    src: ~/project/backend.tar
    dest: /home/ubuntu/web

- name: Execute node
  become_user: ubuntu
  shell: |
    cd /home/ubuntu/web/backend
    npm i
    npm run build
    pm2 start npm -- run  start